<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="description" content="">
  <meta name="keywords" content="">

  <meta name="author" content="Volkker Tech">
  <?php echo $this->tag->getTitle() ?>

  <?php $this->assets->outputCss('header') ?>
  <?php $this->assets->outputJs('header') ?>
</head>

<body>

  <main>
    <?php echo $this->getContent(); ?>
  </main>


  <?php $this->assets->outputJs('footer') ?>
</body>

</html>